language: node_js
node_js:
  - "5.3"
compiler: clang-3.7
env:
  - CXX=clang-3.7
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
before_script:
  - cd src
deploy:
  provider: heroku
  api_key: 3b3a9841-b503-4133-9c8c-6f21d7b5e756
